### ISSUE TITLE
Izuvinimo perziuros duomenu atnaujinimas

### ISSUE THREAD

**Issue by ambrazasp** [AplinkosMinisterija/biip-zuvinimas-api#46]
`POST /fishStockings/review`:

![Image](https://github.com/AplinkosMinisterija/biip-zuvinimas-api/assets/25932455/0e9e556e-bb01-4c24-8bb4-d14cc50a99ee)

- [ ] Neturi buti galimybes ivesti skaiciaus su kableliu (reviewAmount) - validacija

**Comment by DovMa** [comment]
Manau kad problema yra kitur. Frontende neturetu but leidziama ivest skaiciu su kableliais i reviewAmount,  nes negalima izuvinti pvz 2,5 zuvies. Izuvinama yra 2 arba 3 zuvys.

**Comment by ambrazasp** [comment]
Geras pastebejimas. Tada reiketu padaryti validacija backend kad nenueitu iki duombazes. 

Tuo paciu susikuriam nauja task'a pataisymui frontend, kad frontend'as pravaliduotu taip pat.
